// FILENAME_MAP - Maps product IDs to Word document filenames with sector folders

export const FILENAME_MAP: { [key: string]: string } = {
  // Care Home Policies
  'p-ch-01': 'care-home/safeguarding-adults-policy.docx',
  'p-ch-02': 'care-home/infection-prevention-control-policy.docx',
  'p-ch-03': 'care-home/medication-management-policy.docx',
  'p-ch-04': 'care-home/fire-safety-policy.docx',
  'p-ch-05': 'care-home/complaints-compliments-policy.docx',
  'p-ch-06': 'care-home/whistleblowing-policy.docx',
  'p-ch-07': 'care-home/equality-diversity-policy.docx',
  'p-ch-08': 'care-home/data-protection-policy.docx',
  'p-ch-09': 'care-home/staff-training-policy.docx',
  'p-ch-10': 'care-home/restraint-restrictive-practice-policy.docx',
  'p-ch-11': 'care-home/nutrition-hydration-policy.docx',
  'p-ch-12': 'care-home/falls-prevention-management-policy.docx',
  'p-ch-13': 'care-home/pressure-ulcer-prevention-policy.docx',
  'p-ch-14': 'care-home/incident-accident-reporting-policy.docx',
  'p-ch-15': 'care-home/end-of-life-care-policy.docx',

  // Care Home Risk Assessments
  'ra-ch-01': 'care-home/fire-safety.docx',
  'ra-ch-02': 'care-home/moving-handling.docx',
  'ra-ch-03': 'care-home/infection-prevention-control.docx',
  'ra-ch-04': 'care-home/falls-prevention-management.docx',
  'ra-ch-05': 'care-home/pressure-ulcer-prevention-skin-integrity.docx',
  'ra-ch-06': 'care-home/chemical-safety.docx',
  'ra-ch-07': 'care-home/safeguarding-adults.docx',
  'ra-ch-08': 'care-home/nutrition-hydration-choking.docx',
  'ra-ch-09': 'care-home/medication-management.docx',
  'ra-ch-10': 'care-home/environmental-hazards.docx',
  'ra-ch-11': 'care-home/legionella.docx',
  'ra-ch-12': 'care-home/allergen.docx',
  'ra-ch-13': 'care-home/lone-working-staff-safety.docx',
  'ra-ch-14': 'care-home/noise-exposure.docx',
  'ra-ch-15': 'care-home/violence-and-aggression.docx',

  // Dental Policies
  'p-dp-01': 'dental/infection-prevention-control-policy.docx',
  'p-dp-02': 'dental/decontamination-policy.docx',
  'p-dp-03': 'dental/radiation-protection-policy.docx',
  'p-dp-04': 'dental/consent-to-treatment-policy.docx',
  'p-dp-05': 'dental/medical-emergencies-policy.docx',
  'p-dp-06': 'dental/local-anaesthesia-administration-policy.docx',
  'p-dp-07': 'dental/patient-records-management-policy.docx',
  'p-dp-08': 'dental/safeguarding-children-vulnerable-adults-policy.docx',
  'p-dp-09': 'dental/equality-diversity-reasonable-adjustments-policy.docx',
  'p-dp-10': 'dental/health-and-safety-policy.docx',
  'p-dp-11': 'dental/complaints-handling-policy.docx',
  'p-dp-12': 'dental/staff-training-cpd-competency-policy.docx',

  // Dental Risk Assessments
  'ra-dp-01': 'dental/cross-infection-control-decontamination-risk-assessment.docx',
  'ra-dp-02': 'dental/dental-handpiece-aerosol-management-risk-assessment.docx',
  'ra-dp-03': 'dental/radiation-protection-dental-radiography-risk-assessment.docx',
  'ra-dp-04': 'dental/conscious-sedation-inhalation-iv-risk-assessment.docx',
  'ra-dp-05': 'dental/dental-amalgam-mercury-handling-risk-assessment.docx',
  'ra-dp-06': 'dental/ergonomic-risk-assessment.docx',
  'ra-dp-07': 'dental/lone-working-in-the-dental-practice-risk-assessment.docx',
  'ra-dp-08': 'dental/manual-handling-musculoskeletal-risks-risk-assessment.docx',
  'ra-dp-09': 'dental/medical-emergencies-in-the-dental-practice-risk-assessment.docx',
  'ra-dp-10': 'dental/radiation-protection-dental-radiography-risk-assessment.docx',
  'ra-dp-11': 'dental/waste-management-risk-assessment.docx',
  'ra-dp-12': 'dental/safeguarding-vulnerable-patients-adults-children-risk-assessment.docx',

  // Aesthetic Clinic Policies
  'p-ac-01': 'aesthetic/consent-risk-disclosure-policy.docx',
  'p-ac-02': 'aesthetic/infection-control-policy.docx',
  'p-ac-03': 'aesthetic/product-management-policy.docx',
  'p-ac-04': 'aesthetic/practitioner-competency-policy.docx',
  'p-ac-05': 'aesthetic/adverse-event-management-policy.docx',
  'p-ac-06': 'aesthetic/client-safeguarding-policy.docx',
  'p-ac-07': 'aesthetic/health-safety-policy.docx',
  'p-ac-08': 'aesthetic/privacy-data-protection-policy.docx',
  'p-ac-09': 'aesthetic/complaints-policy.docx',
  'p-ac-10': 'aesthetic/marketing-advertising-policy.docx',

  // Aesthetic Clinic Risk Assessments
  'ra-ac-01': 'aesthetic/infection-prevention-control-ipc.docx',
  'ra-ac-02': 'aesthetic/botulinum-toxin-botox-administration.docx',
  'ra-ac-03': 'aesthetic/dermal-filler-treatments.docx',
  'ra-ac-04': 'aesthetic/chemical-skin-peels.docx',
  'ra-ac-05': 'aesthetic/cryotherapy-cryolipolysis-fat-freezing.docx',
  'ra-ac-06': 'aesthetic/laser-intense-pulsed-light-ipl-treatments.docx',
  'ra-ac-07': 'aesthetic/microneedling-collagen-induction-therapy.docx',
  'ra-ac-08': 'aesthetic/patient-consultation-consent-data-protection.docx',
  'ra-ac-09': 'aesthetic/platelet-rich-plasma-prp-therapy.docx',
  'ra-ac-10': 'aesthetic/thread-lift-procedures-pdo-plla-pcl-threads.docx',

  // GP Practice Policies
  'p-gp-01': 'gp/data-protection-and-information-governance.docx',
  'p-gp-02': 'gp/medicines-management.docx',
  'p-gp-03': 'gp/fire-safety.docx',
  'p-gp-04': 'gp/infection-prevention-and-control.docx',
  'p-gp-05': 'gp/safeguarding-children-and-adults-at-risk.docx',
  'p-gp-06': 'gp/consent-and-confidentiality.docx',
  'p-gp-07': 'gp/complaints-handling.docx',
  'p-gp-08': 'gp/health-and-safety.docx',

  // GP Practice Risk Assessments
  'ra-gp-01': 'gp/cosh-control-of-substances-hazardous-to-health.docx',
  'ra-gp-02': 'gp/data-protection-and-information-governance.docx',
  'ra-gp-03': 'gp/display-screen-equipment-dse.docx',
  'ra-gp-04': 'gp/fire-safety.docx',
  'ra-gp-05': 'gp/infection-prevention-and-control.docx',
  'ra-gp-06': 'gp/lone-working.docx',
  'ra-gp-07': 'gp/manual-handling.docx',
  'ra-gp-08': 'gp/medicines-management-and-storage.docx',

  // Private Clinic Policies
  'p-pc-01': 'private-clinic/business-continuity-and-emergency-plan.docx',
  'p-pc-02': 'private-clinic/clinical-governance-policy.docx',
  'p-pc-03': 'private-clinic/complaints-handling-policy.docx',
  'p-pc-04': 'private-clinic/consent-to-treatment-policy.docx',
  'p-pc-05': 'private-clinic/data-protection-and-confidentiality-policy.docx',
  'p-pc-06': 'private-clinic/health-and-safety-policy.docx',
  'p-pc-07': 'private-clinic/infection-prevention-and-control-policy.docx',
  'p-pc-08': 'private-clinic/medicines-management-policy.docx',
  'p-pc-09': 'private-clinic/safeguarding-adults-policy.docx',
  'p-pc-10': 'private-clinic/staffing-and-recruitment-policy.docx',

  // Private Clinic Risk Assessments
  'ra-pc-01': 'private-clinic/cosh.docx',
  'ra-pc-02': 'private-clinic/fire-safety.docx',
  'ra-pc-03': 'private-clinic/infection-control.docx',
  'ra-pc-04': 'private-clinic/information-governance-cyber.docx',
  'ra-pc-05': 'private-clinic/lone-working.docx',
  'ra-pc-06': 'private-clinic/manual-handling.docx',
  'ra-pc-07': 'private-clinic/medical-equipment-devices.docx',
  'ra-pc-08': 'private-clinic/medicines-storage-handling.docx',
  'ra-pc-09': 'private-clinic/slips-trips-falls.docx',
  'ra-pc-10': 'private-clinic/violence-aggression.docx',
};