// scripts/scanDriveFiles.js
// Run with: node scripts/scanDriveFiles.js
// Requires GOOGLE_DRIVE_API_KEY in .env.local

const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.join(process.cwd(), '.env.local') });

const DRIVE_FOLDERS = {
  'aesthetic-policies': '1DdfJcQe5ffo-fMbDcY2-8Wn3w0OW0J64',
  'aesthetic-ras': '1yc8T3OmFXXJk0yW63k_GVWvMxLk65xdr',
  'gp-policies': '18Nh1iHqpJE22lhuF1MiNW-pgLgf22Tee',
  'gp-ras': '1_3yMI1fv4MH5Lc6OnNTEOtKi1fVgCFtn',
  'private-health-policies': '1R_LlLqo2sX1OvhSXYKtu5aVA7-c44k4L',
  'private-health-ras': '1Gpucb03Krz0A4p-WanqxkHXpOvuxsOgj',
  'adhd-policies': '1ft5Uh7MBofD1QmQQCugDE5My4R6tiXVX',
  'adhd-ras': '1qD7gNeM1o7ARuK5NgKv-se6Ujr_Dbdlj',
  'weightloss-policies': '1eaLDtwq7MBFeRBSBrcbfpaFcCv4U2pwv',
  'weightloss-ras': '1mCaCsxgpdHhf8v3e6L-NQIsSfihZiiTE',
  'telehealth-policies': '1k75mexfdaf-ZyCIHl-_Ktu7QR9oKaBwl',
  'telehealth-ras': '1sNrbcJhtcV9xReix9Tn7CrKbCrKQxBf1',
};

async function listFilesInFolder(folderId) {
  try {
    const apiKey = process.env.GOOGLE_DRIVE_API_KEY;
    if (!apiKey) {
      console.error('❌ GOOGLE_DRIVE_API_KEY not found in .env.local');
      process.exit(1);
    }

    const response = await fetch(
      `https://www.googleapis.com/drive/v3/files?q='${folderId}'+in+parents&fields=files(id,name)&key=${apiKey}`
    );

    if (!response.ok) {
      console.error(`Error fetching folder ${folderId}:`, response.statusText);
      return [];
    }

    const data = await response.json();
    return (data.files || []).map(f => ({ name: f.name, id: f.id }));
  } catch (error) {
    console.error(`Failed to scan folder ${folderId}:`, error.message);
    return [];
  }
}

function generateProductId(folderCategory, index) {
  const [sector, type] = folderCategory.split('-');
  const sectorPrefix = sector === 'private' ? 'ph' : sector.substring(0, 3);
  const typePrefix = type === 'policies' ? 'pol' : 'ra';
  return `${sectorPrefix}-${typePrefix}-${String(index + 1).padStart(3, '0')}`;
}

async function scanAllFolders() {
  console.log('🔍 Scanning Google Drive folders...\n');

  const allMappings = {};
  const folderContents = {};

  for (const [category, folderId] of Object.entries(DRIVE_FOLDERS)) {
    console.log(`📁 Scanning ${category}...`);
    const files = await listFilesInFolder(folderId);

    if (files.length === 0) {
      console.warn(`   ⚠️  No files found`);
      continue;
    }

    folderContents[category] = {
      folderName: category,
      files: files,
    };

    files.forEach((file, index) => {
      const productId = generateProductId(category, index);
      allMappings[productId] = file.id;
      console.log(`   ✓ ${productId}: ${file.name}`);
    });

    console.log();
  }

  // Generate TypeScript file
  const tsContent = `// lib/driveFileMapping.ts
// Auto-generated by scripts/scanDriveFiles.js
// Last updated: ${new Date().toISOString()}

export const DRIVE_FOLDER_IDS = {
  root: '1lnurWzdSfUZh_fFzbXUlHkZ_J7ZTriiL',
  'aesthetic-policies': '1DdfJcQe5ffo-fMbDcY2-8Wn3w0OW0J64',
  'aesthetic-ras': '1yc8T3OmFXXJk0yW63k_GVWvMxLk65xdr',
  'gp-policies': '18Nh1iHqpJE22lhuF1MiNW-pgLgf22Tee',
  'gp-ras': '1_3yMI1fv4MH5Lc6OnNTEOtKi1fVgCFtn',
  'private-health-policies': '1R_LlLqo2sX1OvhSXYKtu5aVA7-c44k4L',
  'private-health-ras': '1Gpucb03Krz0A4p-WanqxkHXpOvuxsOgj',
  'adhd-policies': '1ft5Uh7MBofD1QmQQCugDE5My4R6tiXVX',
  'adhd-ras': '1qD7gNeM1o7ARuK5NgKv-se6Ujr_Dbdlj',
  'weightloss-policies': '1eaLDtwq7MBFeRBSBrcbfpaFcCv4U2pwv',
  'weightloss-ras': '1mCaCsxgpdHhf8v3e6L-NQIsSfihZiiTE',
  'telehealth-policies': '1k75mexfdaf-ZyCIHl-_Ktu7QR9oKaBwl',
  'telehealth-ras': '1sNrbcJhtcV9xReix9Tn7CrKbCrKQxBf1',
};

export const PRODUCT_FILE_IDS: Record<string, string> = {
${Object.entries(allMappings)
  .map(([productId, fileId]) => `  '${productId}': '${fileId}',`)
  .join('\n')}
};

export function getGoogleDriveFileId(productId: string): string | null {
  return PRODUCT_FILE_IDS[productId] || null;
}

export function getFolderIdByCategory(category: string): string | null {
  return DRIVE_FOLDER_IDS[category as keyof typeof DRIVE_FOLDER_IDS] || null;
}
`;

  const outputPath = path.join(process.cwd(), 'lib', 'driveFileMapping.ts');
  fs.writeFileSync(outputPath, tsContent);

  console.log(`\n✅ Generated ${outputPath}`);
  console.log(`📊 Total products mapped: ${Object.keys(allMappings).length}`);

  // Generate JSON report
  const reportPath = path.join(process.cwd(), 'scripts', 'drive-file-report.json');
  fs.writeFileSync(reportPath, JSON.stringify({ folderContents, allMappings }, null, 2));
  console.log(`📋 Report saved to ${reportPath}`);
}

scanAllFolders().catch(error => {
  console.error('❌ Scan failed:', error);
  process.exit(1);
});
